### ISSUE TITLE
Crear Luka&Kanade con eventos

### ISSUE THREAD

**Issue by davidastur94** [DGMonkeyKing/TFG#11]
Crear variante del codigo host de luka&kanade usando eventos para ver los resultados.

**Comment by DGMonkeyKing** [comment]
Puedes hacerlo ya con lo que teníamos hecho antes. Si quieres puedes hacer una de estas dos cosas:

- Crear un nuevo _main_ 

En el que uses eventos **(Esto lo veo peor, ya que entonces tienes que hacer uno nuevo para eventos con memoria local y eventos con memoria global)**

- Modificar el _main_ actual 

Para que, pasandole un parámetro, se pueda usar eventos o no **(Lo mismo sería aplicable para memoria local, con un solo parámetro ya sabes si hacer memoria local o global).**

**Comment by davidastur94** [comment]
Completado!!!!
