### ISSUE TITLE
Generar Makefile

### ISSUE THREAD

**Issue by DGMonkeyKing** [DGMonkeyKing/TFG#20]
Explicativo por si solo, hombre.

**Comment by davidastur94** [comment]
Hay plugins en code::blocks las cuales sirven para generarlo ya me dirás.

**Comment by DGMonkeyKing** [comment]
Lo acabo de terminar. Lo he probado con la versión del host actual y compila estupendamente... Aunque claro, da problema de ejecución. Tienes que actualizar el host hombre ya.
