### ISSUE TITLE
Cambiar función medida del tiempo (Para Linux)

### ISSUE THREAD

**Issue by DGMonkeyKing** [DGMonkeyKing/TFG#25]
Usar una función para caluclar el tiempo u otra dependiendo de linux o windows

**Comment by DGMonkeyKing** [comment]
http://www.iteramos.com/pregunta/19530/como-calcular-el-tiempo-de-ejecucion-de-un-fragmento-de-codigo-en-c

**Comment by davidastur94** [comment]
Terminado!!!!
